#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments provided, usage:"
    echo "docker/scripts/down [--purge|removes image too] [lab name|e.g. datalab]"
    exit 1
fi

if [ $1 == "--purge" ]; then
    docker rm -f $2
    docker rmi -f yansongsongsong/csapp:$2
else
    docker rm -f $1
fi
