#!/bin/bash

LAB=$1

if [ $# -eq 0 ]; then
    echo "No arguments provided, usage:"
    echo "docker/scripts/up [lab name|e.g. datalab]"
    exit 1
fi

docker run --privileged -d \
    -p 1221:22 \
    -v $(find ${PWD}/**/${LAB}-handout | head -n 1)/root/${LAB}-handout \
    --name ${LAB} \
    yansongsongsong/csapp:${LAB}

docker exec -it ${LAB} /bin/zsh
